### ISSUE TITLE
issue of sorting stacked images in Rasterviewer

### ISSUE THREAD

**Issue by jeosnes** [johntruckenbrodt/spatialist#20]
Hi,

I am using Rasterviewer for the interactive plotting of a stack of Sentinel-1 data (coherence time series in ENVI format). The problem is that although the stack is sorted by date of acquisition, in the rasterviewer sorting is done according to Sentinel-1 A and Sentinel-1 B. Meaning that in the slider first the sorted S1A images are listed then comes S1B images. 
Since I am dealing with coherence images(combination of two image), my bandnames in the header looks like this:
S1A_20201502T160245_S1B_20201506T160326

I edited the header file and took only the first date, i.e. 20201502, it seems that it has no impact on  sorting. 
Could you tell how to fix this issue? 
thank you in advance.

**Comment by johntruckenbrodt** [comment]
Hi @jeosnes,
thanks for reporting this! I just had a look at the code to find where this might be coming from.
I am not sure, but are you using custom band indices with the argument `band_indices`? These were sorted resulting in what you describe. I admit this is not a good idea and have just fixed this in commit 6cbd4c4.
Cheers,
John

**Comment by johntruckenbrodt** [comment]
Closing this for now after two months of inactivity.
