### ISSUE TITLE
Unable to load extension (sqlite3.Connection)

### ISSUE THREAD

**Issue by ibaris** [johntruckenbrodt/spatialist#3]
When I tried to import the package `pyroSAR`, the package `spatialist` caused this error: 
```
Traceback (most recent call last):
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-225f6e7efdf2>", line 1, in <module>
    conn.enable_load_extension(True)
AttributeError: 'sqlite3.Connection' object has no attribute 'enable_load_extension'
```
Within conda the package `pysqlite2` is not installed. Command 'conda install pysqlite' does not work. After trying to install it with pip this message appeared:
```
xxx@yyy:~$ pip install pysqlite2
Collecting pysqlite2
  Could not find a version that satisfies the requirement pysqlite2 (from versions: )
No matching distribution found for pysqlite2
```
After a very long search, I came across a pysqlite package in Anaconda Cloud:
```
conda install -c kbchoi pysqlite
```

# My question is this: 
* Is it necessary for package `pyroSAR` to directly issue an error just because you can't load package `spatialist` ? 
* Is there an alternative to how to work around this problem? 
* Is it possible that this is a Linux Ubuntu 18.10 problem? With Ubuntu 18.04 I unfortunately didn't try it.
* Could it be that I have installed conda in my home directory and not in usr/bin?

**Comment by ibaris** [comment]
With Windows it works pretty good. But wit Ubuntu I get `AttributeError: 'sqlite3.Connection' object has no attribute 'enable_load_extension'`

**Comment by johntruckenbrodt** [comment]
Hi Ismail.
This is the kind of issue that pops up again sometimes. Sqlite and loading spatialite as extension is always a bit trouble.
Yet it's actually quite strange that this happens in a newer version of Ubuntu. It has usually to do with a too old version of sqlite3. Could you try updating it or just using Python3? Python2 is not really well supported by spatialist anymore.
I also never worked with conda under ubuntu. pysqlite2 is only needed if your sqlite3 version is too old and you cannot update it. Have a look at the installation she'll script in spatialist for how to build it with a static sqlite3 build.
The functionalty of spatialist is quite an essential component of pyroSAR thus it's better to leave it like that.
Cheers
